version: "3"
services:
    whatsapp-chatgpt:
        container_name: whatsapp-chatgpt
        read_only: true
        image: ghcr.io/askrella/whatsapp-chatgpt:master
        environment:
            OPENAI_API_KEY: "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"
            OPENAI_GPT_MODEL: "gpt-3.5-turbo"
            PREFIX_ENABLED: "false"
            SERPAPI_API_KEY: ""
        restart: unless-stopped
        volumes:
            - session-data:/app/session
volumes:
    session-data:
